### ISSUE TITLE
Create module for building minting tx request

### ISSUE THREAD

**Issue by jaysee260** [ergonames/ergo-names-old-webapp#1]
We need to build a minting request on behalf of the user, and send it to the contract address.

The minting request is just a box that needs to have certain pieces of information in its registers. The [minting contract](https://github.com/ergonames/ergo-names-backend/blob/master/src/main/scala/contracts/ErgoNamesMintingContract.scala) has documentation showing what needs to go on each register.

**Comment by zackbalbin** [comment]
initial version (0.1.0) of new module can be found here https://www.npmjs.com/package/ergonames-tx-lib

repo https://github.com/ergonames/transaction-builder

**Comment by zackbalbin** [comment]
Transaction successfully sent using module 
https://testnet.ergoplatform.com/en/transactions/0baece20157c9e9cbdbf981305f78aea4e065acdd23abc2a961df1287575454c
